# Generated by Django 2.2.16 on 2020-09-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='gmap_url',
            field=models.CharField(default='', max_length=255, verbose_name='Google map URL'),
            preserve_default=False,
        ),
    ]
