# Generated by Django 2.2.16 on 2020-10-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_venue_gmap_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Event Name'),
        ),
    ]
