# Generated by Django 2.2.16 on 2020-10-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20201031_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='gmap_embed',
            field=models.TextField(default='', verbose_name='Google map Embed'),
        ),
    ]
