# Generated by Django 2.2.16 on 2020-10-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_venue_gmap_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dt_countdown',
            field=models.DateTimeField(default=None, null=True, verbose_name='Countdown'),
        ),
    ]
