# Generated by Django 2.2.16 on 2020-10-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_dt_countdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gcal_link',
            field=models.TextField(default='', verbose_name='Google Calendar Link'),
        ),
    ]
