# Generated by Django 2.2.16 on 2020-10-31 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_event_gcal_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congratulationwhises',
            name='invitation',
        ),
        migrations.AddField(
            model_name='congratulationwhises',
            name='event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Event', verbose_name='Event'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Name')),
                ('phone', models.CharField(default='', max_length=16, verbose_name='Phone')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='Email')),
                ('is_attend', models.BooleanField(default=False)),
                ('guest', models.PositiveIntegerField(default=1)),
                ('event', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Event', verbose_name='Event')),
            ],
        ),
    ]
