# Generated by Django 2.2.16 on 2020-10-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20201031_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='whises',
            field=models.TextField(default='', verbose_name='Whises'),
        ),
    ]
