# Generated by Django 2.2.16 on 2020-11-20 14:08

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_attendance_whises'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='event',
            name='meta_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=event.models.UploadImage('event-images/')),
        ),
    ]
